### ISSUE TITLE
Scope SRE access to just ROSA resources where possible

### ISSUE THREAD

**Issue by nccurry** [openshift/rosa#438]
We should further scope down the *-Support-Role
https://github.com/openshift/rosa/blob/master/templates/policies/4.7/sts_support_permission_policy.json
https://github.com/openshift/rosa/blob/master/templates/policies/4.8/sts_support_permission_policy.json
https://github.com/openshift/rosa/blob/master/templates/policies/4.9/sts_support_permission_policy.json

The following permissions can be scoped to just resources with the red-hat-managed: true AWS tag. 

```yaml
- Effect: Allow
  Action:
  - ec2:CreateSnapshots
  - ec2:GetAssociatedIpv6PoolCidrs
  - ec2:GetTransitGatewayAttachmentPropagations
  - ec2:GetTransitGatewayMulticastDomainAssociations
  - ec2:GetTransitGatewayPrefixListReferences
  - ec2:GetTransitGatewayRouteTableAssociations
  - ec2:GetTransitGatewayRouteTablePropagations
  - ec2:RebootInstances
  - ec2:SearchLocalGatewayRoutes
  - ec2:SearchTransitGatewayMulticastGroups
  - ec2:SearchTransitGatewayRoutes
  - ec2:StartInstances
  - ec2:TerminateInstances
  Condition:
    StringEquals:
      aws:ResourceTag/red-hat-managed: 'true'
  Resource: '*'
```

This will help assure Red Hat customer's that Red Hat SRE team cannot cause issues with infrastructure that is not related to ROSA.
